apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
  namespace: python-app
spec:
  selector:
    matchLabels:
      app: mysql-app
  template:
    metadata:
      labels:
        app: mysql-app
    spec:
      containers:
      - name: mysql
        image: mysql:8
        env:
          - name: MYSQL_USER
            value: flaskuser
          - name: MYSQL_DATABASE
            value: mydatabase
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-db-config
                key: MYSQL_PASSWORD
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-db-config
                key: MYSQL_ROOT_PASSWORD
        ports:
        - containerPort: 3306
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: python-app
spec:
  selector:
    app: mysql-app
  ports:
  - port: 3306

