apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deploy
  namespace: python-app
spec:
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: conjunrad/test_project:websql-app
        env:
          - name: DB_HOST
            value: mysql-svc
          - name: MYSQL_USER
            value: flaskuser
          - name: MYSQL_DATABASE
            value: mydatabase
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-db-config
                key: MYSQL_PASSWORD
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-db-config
                key: MYSQL_ROOT_PASSWORD
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: python-app-svc
  namespace: python-app
spec:
  type: LoadBalancer
  selector:
    app: python-app
  ports:
  - port: 5000
